ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data/denoiseIdeal.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wdeconv(ops, S);
writematrix(sp, '~/Downloads/personalRepo/Cov/Data/suite2P_denoiseIdeal.csv');
ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data2/denoiseIdeal.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wdeconv(ops, S);
writematrix(sp, '~/Downloads/personalRepo/Cov/Data2/suite2P_denoiseIdeal.csv');

ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data3/denoiseIdeal.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wdeconv(ops, S);
writematrix(sp,'~/Downloads/personalRepo/Cov/Data3/suite2P_denoise.csv');


%%
ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data/soma.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wrapperDECONV(ops, S);
writematrix(sp, '~/Downloads/personalRepo/Cov/Data/suite2P_soma.csv');
ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data/idealTraces.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wrapperDECONV(ops, S);
writematrix(sp, '~/Downloads/personalRepo/Cov/Data/suite2P_ideal.csv');

ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data2/soma.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wrapperDECONV(ops, S);
writematrix(sp,'~/Downloads/personalRepo/Cov/Data2/suite2P_soma.csv');
ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data2/idealTraces.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wrapperDECONV(ops, S);
writematrix(sp,'~/Downloads/personalRepo/Cov/Data2/suite2P_ideal.csv');

ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data3/soma.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wrapperDECONV(ops, S);
writematrix(sp, '~/Downloads/personalRepo/Cov/Data3/suite2P_soma.csv');
ops = struct();
ops.fs = 30;
ops.estimateNeuropil = 0;
ops.sensorTau = 600;
S = readmatrix('~/Downloads/personalRepo/Cov/Data3/idealTraces.csv');
S = S(1:338, :);
S = S.';
[sp, ca, coefs, B, sd, ops, baselines] = wrapperDECONV(ops, S);
writematrix(sp, '~/Downloads/personalRepo/Cov/Data3/suite2P_ideal.csv');
